package com.compose.example.design

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

//Grayscale light color scheme
val lightWhiteColorScheme = lightColorScheme(
    primary = white[40],
    onPrimary = white[100],
    primaryContainer = white[90],
    onPrimaryContainer = white[10],
    inversePrimary = white[80],
    primaryFixed = white[90],
    primaryFixedDim = white[80],
    onPrimaryFixed = white[10],
    onPrimaryFixedVariant = white[30],
    secondary = white[40],
    onSecondary = white[100],
    secondaryContainer = white[90],
    onSecondaryContainer = white[10],
    secondaryFixed = white[90],
    secondaryFixedDim = white[80],
    onSecondaryFixed = white[10],
    onSecondaryFixedVariant = white[30],
    tertiary = white[40],
    onTertiary = white[100],
    tertiaryContainer = white[90],
    onTertiaryContainer = white[10],
    tertiaryFixed = white[90],
    tertiaryFixedDim = white[80],
    onTertiaryFixed = white[10],
    onTertiaryFixedVariant = white[30],
    background = white[98],
    onBackground = white[10],
    surface = white[98],
    onSurface = white[10],
    surfaceTint = white[40],
    inverseSurface = white[20],
    inverseOnSurface = white[95],
    scrim = white[0],
    surfaceBright = white[98],
    surfaceContainer = white[94],
    surfaceContainerHigh = white[92],
    surfaceContainerHighest = white[90],
    surfaceContainerLow = white[96],
    surfaceContainerLowest = white[100],
    surfaceDim = white[87],
    surfaceVariant = white[90],
    onSurfaceVariant = white[30],
    outline = white[50],
    outlineVariant = white[80],
    error = white[40],
    onError = white[100],
    errorContainer = white[90],
    onErrorContainer = white[10]
)

//Grayscale dark color scheme
val darkWhiteColorScheme = darkColorScheme(
    primary = white[80],
    onPrimary = white[20],
    primaryContainer = white[30],
    onPrimaryContainer = white[90],
    inversePrimary = white[40],
    primaryFixed = white[90],
    primaryFixedDim = white[80],
    onPrimaryFixed = white[10],
    onPrimaryFixedVariant = white[30],
    secondary = white[80],
    onSecondary = white[20],
    secondaryContainer = white[30],
    onSecondaryContainer = white[90],
    secondaryFixed = white[90],
    secondaryFixedDim = white[80],
    onSecondaryFixed = white[10],
    onSecondaryFixedVariant = white[30],
    tertiary = white[80],
    onTertiary = white[20],
    tertiaryContainer = white[30],
    onTertiaryContainer = white[90],
    tertiaryFixed = white[90],
    tertiaryFixedDim = white[80],
    onTertiaryFixed = white[10],
    onTertiaryFixedVariant = white[30],
    background = white[6],
    onBackground = white[90],
    surface = white[6],
    onSurface = white[90],
    surfaceTint = white[80],
    inverseSurface = white[90],
    inverseOnSurface = white[20],
    scrim = white[0],
    surfaceBright = white[24],
    surfaceContainer = white[12],
    surfaceContainerHigh = white[17],
    surfaceContainerHighest = white[22],
    surfaceContainerLow = white[10],
    surfaceContainerLowest = white[4],
    surfaceDim = white[6],
    surfaceVariant = white[30],
    onSurfaceVariant = white[80],
    outline = white[60],
    outlineVariant = white[30],
    error = white[80],
    onError = white[20],
    errorContainer = white[30],
    onErrorContainer = white[90]
)