package com.compose.example.design.scheme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import com.compose.example.tone

//Grayscale light color scheme
val lightWhiteColorScheme = ColorScheme(
    primary = Color.White.tone(40.0),
    onPrimary = Color.White.tone(100.0),
    primaryContainer = Color.White.tone(90.0),
    onPrimaryContainer = Color.White.tone(10.0),
    inversePrimary = Color.White.tone(80.0),
    primaryFixed = Color.White.tone(90.0),
    primaryFixedDim = Color.White.tone(80.0),
    onPrimaryFixed = Color.White.tone(10.0),
    onPrimaryFixedVariant = Color.White.tone(30.0),
    secondary = Color.White.tone(40.0),
    onSecondary = Color.White.tone(100.0),
    secondaryContainer = Color.White.tone(90.0),
    onSecondaryContainer = Color.White.tone(10.0),
    secondaryFixed = Color.White.tone(90.0),
    secondaryFixedDim = Color.White.tone(80.0),
    onSecondaryFixed = Color.White.tone(10.0),
    onSecondaryFixedVariant = Color.White.tone(30.0),
    tertiary = Color.White.tone(40.0),
    onTertiary = Color.White.tone(100.0),
    tertiaryContainer = Color.White.tone(90.0),
    onTertiaryContainer = Color.White.tone(10.0),
    tertiaryFixed = Color.White.tone(90.0),
    tertiaryFixedDim = Color.White.tone(80.0),
    onTertiaryFixed = Color.White.tone(10.0),
    onTertiaryFixedVariant = Color.White.tone(30.0),
    background = Color.White.tone(98.0),
    onBackground = Color.White.tone(10.0),
    surface = Color.White.tone(98.0),
    onSurface = Color.White.tone(10.0),
    surfaceTint = Color.White.tone(40.0),
    inverseSurface = Color.White.tone(20.0),
    inverseOnSurface = Color.White.tone(95.0),
    scrim = Color.White.tone(0.0),
    surfaceBright = Color.White.tone(98.0),
    surfaceContainer = Color.White.tone(94.0),
    surfaceContainerHigh = Color.White.tone(92.0),
    surfaceContainerHighest = Color.White.tone(90.0),
    surfaceContainerLow = Color.White.tone(96.0),
    surfaceContainerLowest = Color.White.tone(100.0),
    surfaceDim = Color.White.tone(87.0),
    surfaceVariant = Color.White.tone(90.0),
    onSurfaceVariant = Color.White.tone(30.0),
    outline = Color.White.tone(50.0),
    outlineVariant = Color.White.tone(80.0),
    error = Color.White.tone(40.0),
    onError = Color.White.tone(100.0),
    errorContainer = Color.White.tone(90.0),
    onErrorContainer = Color.White.tone(100.0)
)

//Grayscale dark color scheme
val darkWhiteColorScheme = ColorScheme(
    primary = Color.White.tone(80.0),
    onPrimary = Color.White.tone(20.0),
    primaryContainer = Color.White.tone(30.0),
    onPrimaryContainer = Color.White.tone(90.0),
    inversePrimary = Color.White.tone(40.0),
    primaryFixed = Color.White.tone(90.0),
    primaryFixedDim = Color.White.tone(80.0),
    onPrimaryFixed = Color.White.tone(10.0),
    onPrimaryFixedVariant = Color.White.tone(30.0),
    secondary = Color.White.tone(80.0),
    onSecondary = Color.White.tone(20.0),
    secondaryContainer = Color.White.tone(30.0),
    onSecondaryContainer = Color.White.tone(90.0),
    secondaryFixed = Color.White.tone(90.0),
    secondaryFixedDim = Color.White.tone(80.0),
    onSecondaryFixed = Color.White.tone(10.0),
    onSecondaryFixedVariant = Color.White.tone(30.0),
    tertiary = Color.White.tone(80.0),
    onTertiary = Color.White.tone(20.0),
    tertiaryContainer = Color.White.tone(30.0),
    onTertiaryContainer = Color.White.tone(90.0),
    tertiaryFixed = Color.White.tone(90.0),
    tertiaryFixedDim = Color.White.tone(80.0),
    onTertiaryFixed = Color.White.tone(10.0),
    onTertiaryFixedVariant = Color.White.tone(30.0),
    background = Color.White.tone(6.0),
    onBackground = Color.White.tone(90.0),
    surface = Color.White.tone(6.0),
    onSurface = Color.White.tone(90.0),
    surfaceTint = Color.White.tone(80.0),
    inverseSurface = Color.White.tone(90.0),
    inverseOnSurface = Color.White.tone(20.0),
    scrim = Color.White.tone(0.0),
    surfaceBright = Color.White.tone(24.0),
    surfaceContainer = Color.White.tone(12.0),
    surfaceContainerHigh = Color.White.tone(17.0),
    surfaceContainerHighest = Color.White.tone(22.0),
    surfaceContainerLow = Color.White.tone(10.0),
    surfaceContainerLowest = Color.White.tone(4.0),
    surfaceDim = Color.White.tone(6.0),
    surfaceVariant = Color.White.tone(30.0),
    onSurfaceVariant = Color.White.tone(80.0),
    outline = Color.White.tone(60.0),
    outlineVariant = Color.White.tone(30.0),
    error = Color.White.tone(80.0),
    onError = Color.White.tone(20.0),
    errorContainer = Color.White.tone(30.0),
    onErrorContainer = Color.White.tone(90.0)
)